connections:
  - {client: 10.0.0.1, server: 10.0.0.2, server_port: 10000}
  - {client: 10.0.0.1, server: 10.0.0.3, server_port: 10000}
  - {client: 10.0.0.2, server: 10.0.0.3, server_port: 12000}
  - {client: 10.0.0.2, server: 10.0.0.1, server_port: 13000}
